#spring.jpa.hibernate.ddl-auto=update
#spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/OTW
#spring.datasource.username=springuser
#spring.datasource.password=opentowork
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
#spring.jpa.show-sql: true

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/OTW
    username: springuser
    password: opentowork
    driver-class-name: com.mysql.cj.jdbc.Driver

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem
